(ns fifth-postulate.core
  (:require fifth-postulate.ns01
            fifth-postulate.ns02
            fifth-postulate.ns03
            fifth-postulate.ns04
            fifth-postulate.ns05
            fifth-postulate.ns06
            fifth-postulate.ns07
            fifth-postulate.ns08
            fifth-postulate.ns09
            fifth-postulate.ns10
            fifth-postulate.ns11
            fifth-postulate.ns12
            fifth-postulate.ns13
            fifth-postulate.ns14
            fifth-postulate.ns15
            fifth-postulate.ns16
            fifth-postulate.ns17
            fifth-postulate.ns18
            fifth-postulate.ns19
            fifth-postulate.ns20
            fifth-postulate.ns21
            fifth-postulate.ns22
            fifth-postulate.ns23
            fifth-postulate.ns24
            fifth-postulate.ns25
            fifth-postulate.ns26
            fifth-postulate.ns27
            fifth-postulate.ns28
            fifth-postulate.ns29
            fifth-postulate.ns30
            fifth-postulate.ns31
            fifth-postulate.ns32
            fifth-postulate.ns33
            fifth-postulate.ns34
            fifth-postulate.ns35
            fifth-postulate.ns36
            fifth-postulate.ns37
            fifth-postulate.ns38
            fifth-postulate.ns39
            fifth-postulate.ns40
            fifth-postulate.ns41
            fifth-postulate.ns42
            fifth-postulate.ns43
            fifth-postulate.ns44
            fifth-postulate.ns45
            fifth-postulate.ns46
            fifth-postulate.ns47
            fifth-postulate.ns48
            fifth-postulate.ns49
            fifth-postulate.ns50
            fifth-postulate.ns51
            fifth-postulate.ns52
            fifth-postulate.ns53
            fifth-postulate.ns54
            fifth-postulate.ns55
            fifth-postulate.ns56
            fifth-postulate.ns57
            fifth-postulate.ns58
            fifth-postulate.ns59
            fifth-postulate.ns60
            fifth-postulate.ns61
            fifth-postulate.ns62
            fifth-postulate.ns63
            fifth-postulate.ns64))
